#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions
#runApplication surfaceFeatureExtract

#runApplication blockMesh

#runApplication decomposePar -copyZero
#runParallel snappyHexMesh -overwrite

#runApplication reconstructParMesh -constant -latestTime
#rm -r processor*

#rm -rf log.decomposePar
#runApplication decomposePar
runParallel $(getApplication)
runApplication reconstructPar -latestTime

#------------------------------------------------------------------------------
